# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oG6F1PZR2XQvEtSoVycx/WmcIw6nbjaVAvUqPzapmeByWbg4qmkzsxoayGvphOVbaQH0L3owpOQBDpZWWF9bl8jEqw2e5zk6D8tSQEk8pa7gWeafAmfzHMzHqlqHEayJw/I7mi4Pnmv9i43fRc/3ZKXa66oLeIlUg6Fx/mq40VZsjDe3QltJ7VeQaa9csmSRLR64fJ+UMFJQNNGoPbS4b9/iltHMY8yarTZ/PfqfJgQKyTp/oRuXYfla7JNqSG7vg1WpFydG+WkVG+bvvmmIcxpI+sQVQsQXfrj6uxAgnnTXmweiMgyJaj03q2PybPXd2876qMDVtYMFG1wP0s51eQSsWlwHNNnYPLbgZtHHZS02rqW2gqKTeiu7fXWXie1Hy7S8VT4JFm6ROoebiez5l/13A3YqCO6TWTEafDdyXaIUOWcwywt34KZF+hMRmN0WU2DSp8A1uS5OYUMfw+ozoVwZuK3WLM1go55+3y8E1NoChgucFv1nDmcEjgDxRUMNLv7GrXXuaytUMnjZy286GL8zcAcdJd/ndueVXLAtQN/T7nNi/aD+Rphvr6j4T+PaRbOqzW7eUVAmHVVSOWDGmJmbaaAszCAqk8mS7aOApfNgCBuaczgWPW7HdalGHAFGJZAtN+NoU1afr2CmyTz//0J+XUgdAfxZ8lMS+/MnwRk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
