travis:
  secure:
    BINSTAR_TOKEN: LB+WwCMkT82rJpDM7bPgFjLNLljYQtmcit2vT0JglRxYGLLumz0IcatsOqEprxRa4OTCTlqHum5OZ4XfLma6TP98JS3jmO3VljIiGZ2VY/7AoFxKQuzFPakGCTwMukU7YXhrcouINfOHlPxtGpjRaNGLFhegfqZSm6AEyfZNiuXpVY9K/XxslZcM4CO+bMiJYCmxPlZhCOqUCnJIRGtI20qZyURpoGB5O2/YMHRsrlI/pgwrKOt8ktl/U2e9zVrW4ONwtRN4Udqf922fCnqcpj7MNGyq7d0VIPqqHcOF6JXmp/E3ni7CcnumB1z/MiHr0IwZ9ikfArNdiIsalC+5b/0zId8iDTi3/3NI65ZId+h45z39Ynehod10dpzTinSDpsTfe/uUP6/ZQNUDtZ8Hi7/0td+V+pjGSTOJiBZtuVZdhYaepkjgbxzrKGi5TkZq6u0lSACeYyiXtika++Xh390NZnFbkHA1IgIGuDGHEbocWqWuu9jVraA9CDHVNpd8pQHuHyhBLb7wb58jSzx/4Gvw1r27yRfs4YNv9RMX43nTubTx4TrMjivVHuzLIgIPHNWfBiLoWUBagGFVabsdjFQTNTCIuFGHBhItXMQ6DkOhwjSNrZuGx9ZuI+L6FQqoSUL2uUbEbtVkVKaUl8+Nh6fHVAi98Ytj29onI5IGO3o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
